name: Test

on:
  schedule:
    - cron: "0 7 * * 0"
  push:

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        version:
          - "1.x"
          - "1.28.x"
    runs-on: ${{ matrix.runner }}
    steps:
      - run: git config --global core.autocrlf false
        if: runner.os == 'Windows'
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "${{ matrix.version }}"
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno
            /home/runner/.cache/deno/deps/https/deno.land
      - name: Test
        run: |
          deno task test
      - name: Type check
        run: |
          deno task check
      - name: Lint check
        run: |
          deno lint
      - name: Format check
        run: |
          deno fmt && git diff --exit-code
      - name: Bench
        run: |
          deno task bench
